name: Daily AI Sales Summary

on:
  schedule:
    - cron: "45 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install torch --index-url https://download.pytorch.org/whl/cpu

    - name: Run script
      run: python improved_flan_ai_sales_summary.py
